### ISSUE TITLE
electron-prompt does not work in electron V10

### ISSUE THREAD

**Issue by godza** [p-sam/electron-prompt#57]
When i try opening electron prompt with even the simplest of parameters i'm getting strange error in console.

This is the sample code
```
    prompt({
      title: 'test',
      label: 'test',
      value: 'test',
      type: 'input'
    });
```

This is the error
```
(node:90465) UnhandledPromiseRejectionWarning: Error: Image could not be created from
    at /private/var/www/activecollab-desktop/node_modules/electron-prompt/lib/index.js:41:22
    at new Promise (<anonymous>)
    at electronPrompt (/private/var/www/activecollab-desktop/node_modules/electron-prompt/lib/index.js:12:9)
    at click (/private/var/www/activecollab-desktop/utils/menu.js:338:5)
    at MenuItem.click (electron/js2c/browser_init.js:1481:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1742:13)
(node:90465) UnhandledPromiseRejectionWarning: Error: Image could not be created from
    at /private/var/www/activecollab-desktop/node_modules/electron-prompt/lib/index.js:41:22
    at new Promise (<anonymous>)
    at electronPrompt (/private/var/www/activecollab-desktop/node_modules/electron-prompt/lib/index.js:12:9)
    at click (/private/var/www/activecollab-desktop/utils/menu.js:338:5)
    at MenuItem.click (electron/js2c/browser_init.js:1481:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1742:13)
(node:90465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:90465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by p-sam** [comment]
Thanks for the heads up, it looks like electron treats the icon in BrowserOptions as set even when null, triggering that error

**Comment by godza** [comment]
That was blazingly fast response and fix. Cheers!
